import{a as P,S as x,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const R="50254801-91971d45cfc13d9e951cbfc82",B="https://pixabay.com/api/";async function p(i,t=1){const o={key:R,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await P.get(B,{params:o})).data}const y=document.querySelector(".loader"),g=document.querySelector(".gallery"),L=document.querySelector(".load-more"),b=document.querySelector(".loading-text");let u=null;function T(){y.classList.remove("visually-hidden")}function f(){y.classList.add("visually-hidden")}function $(){g.innerHTML=""}function v(){L.classList.remove("visually-hidden")}function c(){L.classList.add("visually-hidden")}function O(){b.classList.remove("visually-hidden")}function w(){b.classList.add("visually-hidden")}function S(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:a,comments:E,downloads:q})=>`<li class="gallery-item">
    <a href="${n}"><img src="${o}" alt="${e}" title=""/></a>
    <div class="cont">
      <p><b>Likes</b><br>${r}</p>
      <p><b>Views</b><br>${a}</p>
      <p><b>Comments</b><br>${E}</p>
      <p><b>Downloads</b><br>${q}</p>
    </div>
</li>`).join("");g.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new x(".gallery a",{captionsData:"alt",captionDelay:250})}const m=document.querySelector("form"),A=document.querySelector(".load-more"),d=40;let l=1,h="";m.addEventListener("submit",async i=>{i.preventDefault(),$(),c(),w(),T();const t=i.currentTarget.elements["search-text"].value.trim();if(!t)return f(),s.error({title:"Error",message:"Please enter a search query.",position:"topRight"});try{h=t,l=1;const o=await p(h,l,d);if(f(),o.hits.length===0)return s.error({title:"Error",message:"Sorry, no images found. Try another keyword!",position:"topRight"});S(o.hits),o.totalHits<=d?(s.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"}),c()):v()}catch{f(),s.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{m.reset()}});A.addEventListener("click",async()=>{l+=1,c(),O();try{const i=await p(h,l,d);S(i.hits),i.totalHits<=l*d?(c(),s.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"})):v();const t=document.querySelector(".gallery").firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{s.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
